[package]
name = "pmpt-hmac-psss"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
num-integer = "0.1"
rand = "0.8"
rand_chacha = "0.3"
rand_distr = "0.4"
sha3 = "0.10"
thiserror = "1.0"
hex = "0.4"
num-bigint = { version = "0.4", features = ["serde","rand"] }
